# Generated by Django 2.2.10 on 2020-02-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboards',
            name='test_field',
        ),
        migrations.RemoveField(
            model_name='districts',
            name='test_field',
        ),
    ]
