# Generated by Django 2.2.10 on 2020-02-18 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_informationforactioncategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationforactioncategory',
            options={'verbose_name_plural': 'Information For Action categories'},
        ),
    ]
