# Generated by Django 2.2.10 on 2020-02-18 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20200218_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InformationForActionCategory',
        ),
    ]
