# Generated by Django 2.2.10 on 2020-02-19 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_informationforactioncategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationforactioncategory',
            name='icon',
        ),
    ]
