# Generated by Django 2.2.10 on 2020-02-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_iabforeclosuresindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationforactionpage',
            name='author',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
