# Generated by Django 2.2.10 on 2020-02-20 02:49

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_informationforactionpage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='iabaffordabilityindexpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='iabdemolitionsindexpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='iabhousingindexpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
