# Generated by Django 2.2.10 on 2020-02-20 02:49

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_auto_20200219_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='iabforeclosuresindexpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
