# Generated by Django 2.2.10 on 2020-02-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_auto_20200219_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationforactionpage',
            name='author',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
