# Generated by Django 2.2.10 on 2020-02-21 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('resources', '0018_auto_20200220_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationforactionpage',
            name='pdf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
